#!/bin/bash

# Exit on error.
set -e

cd $WORKSPACE_ROOT_DIR

$GRIND repo base_environment

if [ ! -f constraints.in ]; then
  echo generating empty 'constraints.in'
  touch constraints.in
fi

source venv/bin/activate

pip-compile

pip-sync
