#!/bin/bash

set -e

cd $WORKSPACE_ROOT_DIR

source venv/bin/activate

if (( $# )) ; then
  TARGETS=( $@ )
else
  TARGETS=( smot )
fi

echo "Code Quality Scans ..."

MYPYPATH=$PWD nbqa mypy smot

mypy "${TARGETS[@]}"

pyre incremental
