#!/bin/bash

set -e

cd $WORKSPACE_ROOT_DIR

source venv/bin/activate

if (( $# )) ; then
  TARGETS=( $@ )
else
  TARGETS=( smot )
fi

echo "Code Quality Scans ..."

mypy "${TARGETS[@]}"

# does not like pytorch
# pyre incremental
