#!/bin/bash

set -e

cd $WORKSPACE_ROOT_DIR

source venv/bin/activate

if (( $# )) ; then
  TARGETS=( $@ )
else
  TARGETS=( $( $HUSTLE changed ) )
fi

PY_TARGETS=()
NB_TARGETS=()

for x in "${TARGETS[@]}"; do
  if [[ -d "$x" ]]; then
    PY_TARGETS+=( "$x" )
    NB_TARGETS+=( "$x" )

  else 
    case "$x" in
      *.py)
        PY_TARGETS+=( "$x" )
	;;

      *.ipynb)
        NB_TARGETS+=( "$x" )
	;;
    esac
  fi
done

if (( ${#PY_TARGETS[@]} )); then
  isort "${PY_TARGETS[@]}"
  yapf -i -r "${PY_TARGETS[@]}"
fi

if (( ${#NB_TARGETS[@]} )); then
  for f in $( find "${NB_TARGETS[@]}" -name '*.ipynb' ); do
    # black_nbconvert makes trivial file changes if you don't do this.
    if ! black_nbconvert --check "$f" > /dev/null; then
      black_nbconvert "$f"
    fi
  done
fi

