#!/bin/bash

set -e
# set -x

cd $WORKSPACE_ROOT_DIR

source venv/bin/activate

if (( $# )) ; then
  TARGETS=( $@ )
else
  TARGETS=( $( $GRIND changed ) )
fi

# TARGETS may contain file or directories that were deleted or moved;
# which obviously cannot be formatted, and need to be excluded.

PY_TARGETS=()
NB_TARGETS=()

for x in "${TARGETS[@]}"; do
  if [[ -d "$x" ]]; then
    PY_TARGETS+=( "$x" )
    NB_TARGETS+=( "$x" )

  elif [[ -f "$x" ]]; then
    case "$x" in
      *.py)
        PY_TARGETS+=( "$x" )
	;;

      *.ipynb)
        NB_TARGETS+=( "$x" )
	;;
    esac
  fi
done

if (( ${#PY_TARGETS[@]} )); then
  autoflake -i -r --remove-all-unused-imports "${PY_TARGETS[@]}"
  isort "${PY_TARGETS[@]}"
  black "${PY_TARGETS[@]}"
fi

if (( ${#NB_TARGETS[@]} )); then
  for f in $( find "${NB_TARGETS[@]}" -name '*.ipynb' ); do
    # black_nbconvert makes trivial file changes if you don't do this.
    if ! black_nbconvert --check "$f" > /dev/null; then
      black_nbconvert "$f"
    fi
  done
fi
